# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: c++
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - gfortran-5

# Conifguration matrix
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9
        - FC_COMPILER=gfortran-4.9

script:
  - mkdir build
  - cd build
  - CC=$CC_COMPILER CXX=$CXX_COMPILER FC=$FC_COMPILER cmake .. && make
  - make clean-transformation transformation test
