sudo: required
dist: trusty
language: cpp
git:
  submodules: false
matrix:
  include:
  - compiler: gcc
    env:
    - CXX_COMPILER=g++-4.9
    - CC_COMPILER=gcc-4.9
    - FC_COMPILER=gfortran-4.9
    - OMPI_CC=gcc-4.9
    - OMPI_FC=gfortran-4.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - g++-4.9
        - gfortran-4.9
        - ant
        - ant-optional
        - cabal-install
        - ghc
cache:
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
before_install:
- git submodule init
- git submodule update
- travis_retry sudo apt-get install -qq openmpi-bin libopenmpi-dev
- cabal update && cabal install ShellCheck
- export PATH=$PATH:$HOME/.cabal/bin
- shellcheck --version
before_script:
- export FC=$FC_COMPILER
- export CC=$CC_COMPILER
- export CXX=$CXX_COMPILER
- export OMPI_CC
- export OMPI_FC
script:
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=$HOME/claw .. && make
- make
- make install
- make clean-transformation transformation test
- cd -
- "./scripts/check_license"
- "./scripts/check_author"
- cd scripts
- "./run.shellcheck"
notifications:
  slack:
    secure: NTIZzmDqsxEInCI7hwFB7uQZXWNTRHkGWIYZO5ZOr+2Tyksrff1j+vEGmHXwtbbFs4OgDTKz8uGfePsBrTdcUmGkMM7QdQm1pkWaA4VU4MJtviOiHkomypURBI3kwofhohRa7mvvAdiWcECkHGgZqtQYVTJve8LcgutNo2Zv0a0d9piTVCugyh3ONP/MvTSt/wRZ1Tkl59pXBpWCsbRDxZzoSh4feohPNwXtIvcvGBPy4jG14rDvrX3FIxFr56/RmBC89ldJuWkSIRHnTR3pm44W8PEduJ55hr+9EvDIDJJmIqlcanAJjbLBT8DZhXA3JbVoz6qF6t4I9daRK29jjaP6AVmPN61NOxL2HzzGTLl5X/7bEQQilBI8i3208jsIA53ZZmEzDkdu52SKUAEEQxEtrdo8ACvkav377MuuCX/LnmWNbvMlNEPmyKLwZNZaBas3s+ANoU1pMe92zw8oaG0MAxB9K2ejZcvwHDwSvXcTbZ5JXdYfmROyPLINf3s8uLJJaDMPLIPROOHMnGRIekLhUd4ELD1mLpPFqa0Z97xr0lIonAQqF2OedL9yCcX97ZDvooKARD0HRL9aqHeuc97RQsQAT1Y1wZ1zoEdZyX/I2338jmpnk2VIEyFH/rm8/OMgbIpHNo6eKIjLoozm8s3VHphl+FItLCdfBJWFVsE=
  email:
    on_success: never
    on_failure: always
