# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp

# Conifguration matrix
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
        sources: ['ubuntu-toolchain-r-test']
        packages:
          - gcc-4.9
          - g++-4.9
          - gfortran-4.9
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9
        - FC=gfortran-4.9

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - make clean-transformation transformation test
